const constants = {
  SET_JSON: 'SET_JSON',
  RESET: 'RESET',
  SET_TAB_WIDTH: 'SET_TAB_WIDTH',
  FORMAT_JSON: 'FORMAT_JSON',
  PARSE_FAILED: 'PARSE_FAILED',
  PARSE_SUCCESS: 'PARSE_SUCCESS',
  PARSE_FIRST_LAYER: 'PARSE_FIRST_LAYER',
  RESET_TREE: 'RESET_TREE',
  APPEND_TO_TREE: 'APPEND_TO_NODES',
  REMOVE_FROM_TREE: 'REMOVE_FROM_TREE',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  URL_ERROR_ONLOAD: 'URL_ERROR_ONLOAD',
  COLLAPSE_ALL: 'COLLAPSE_ALL',
  LOAD_DEMO: 'LOAD_DEMO',
  SAVE_TO_LOCALSTORAGE: 'SAVE_TO_LOCALSTORAGE'
};

export default constants;
