const constants = {
  SET_JSON: 'SET_JSON',
  FORMAT_JSON: 'FORMAT_JSON',
  PARSE_FIRST_LAYER: 'PARSE_FIRST_LAYER',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  URL_ERROR_ONLOAD: 'URL_ERROR_ONLOAD'
};

export default constants;
